Tear Down Class, Cleanup after test.py
kiat/codeAssist pull request #85
Opened 2024-07-09 15:42 UTC by hudsonwhipple

Test.py
- Teardown class added
- Calls to deletion endpoints

User.py, two new endpoints
- delete_instructor
- delete_student

Documentation for endpoints

2024-07-09 16:31 UTC, defkorean commented on backend/test.py
> +env_file = "http://localhost:5000"
We could probably add this environmental variable to the .env file in backend/.env since other developers may have a different url

2024-07-09 17:17 UTC, defkorean commented
While trying to run the test script, I run into an error where there's invalid json data. I've tried running in virtual environments and local environment and deleting/adding back docker containers but it produces the same traceback here:
<img width="881" alt="Screenshot 2024-07-09 at 12 15 59 PM" src="https://github.com/kiat/codeAssist/assets/85882553/cdce9ad9-cc81-4962-ad74-2c7d1d10d416">

If anyone else is running into this or has a fix please let me know. Otherwise the code and documentation itself looks good, I just can't run the script.

2024-07-18 17:15 UTC, Vellankijay requested changes
Hey Hudson, the implementation as is on the original code is working. However, with my changes to the database and centralizing all of the users under one table needs one simple revision. If you need assistance, please have a look at my branch jay_vellanki. 

Example of how the people's table changes logging in people:
<img width="628" alt="Screenshot 2024-07-18 at 12 15 28 PM" src="https://github.com/user-attachments/assets/001f791f-0e6f-4c98-bd52-076115886594">


The only changes you have to make to your code is in user.py and test.py. In user.py, just implement one delete method for all people. This is simple, can be done by replacing all instructor related table calls with people's table. As for the test.py, just write a test case testing the method.

2024-07-25 20:12 UTC, defkorean commented
> While trying to run the test script, I run into an error where there's invalid json data. I've tried running in virtual environments and local environment and deleting/adding back docker containers but it produces the same traceback here: <img alt="Screenshot 2024-07-09 at 12 15 59 PM" width="881" src="https://private-user-images.githubusercontent.com/85882553/347053849-cdce9ad9-cc81-4962-ad74-2c7d1d10d416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MzczOTYsIm5iZiI6MTcyMTkzNzA5NiwicGF0aCI6Ii84NTg4MjU1My8zNDcwNTM4NDktY2RjZTlhZDktY2M4MS00OTYyLWFkNzQtMmM3ZDFkMTBkNDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE5NTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNzYyZGYzZGRiODhkNzU1NTg5OTUyNzY0NDkxY2UwYWQ1N2M3YjdiYjRiNGFmZjlhYzcxMzAwNjJkNzJiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U73mx0Rjvx--0j84BtngbM9dsGiGRXPe4jfL5XVlPL4">
> 
> If anyone else is running into this or has a fix please let me know. Otherwise the code and documentation itself looks good, I just can't run the script.

It turns out that this issue can be reproduced if you ran the test script before these changes. After deleting all the rows to get a fresh database, I was able to run the test script multiple times. Other than the proposed changes above, I think it's good to merge.

2024-07-25 20:36 UTC, kiat commented
We do this PR after changes to the database structure.

2024-08-13 18:53 UTC, closed without merging