Changes to the Database
kiat/codeAssist pull request #94
Opened 2024-07-19 07:34 UTC by Vellankijay

I've made changes to the structure of the database. The new format centralizes all of the users under one table. Additionally, the tables and API endpoints that are no longer needed have been removed. Further expected change is that the frontend implementation of the Login has been generalized and doesn't depend on the role of the person. These changes shouldn't affect the functioning of the application before the updates.

Changes to come:
- A frontend implementation of the TA's (shouldn't affect the current operations)
- Addition of any user to the course (shouldn't affect the current operations)

2024-07-23 19:20 UTC, defkorean commented
If I'm not wrong, the change to the database is a reflection of issue ticket #38 correct? Also, just to clarify, the "changes to come" is referring to the changes that you made through these two commits and are awaiting for review in this pull request?

2024-07-24 19:23 UTC, logankimm commented
For TA implementation, wouldn't it be better to
1. For the role, only make it so can be a binary choice between teacher and student
2. Add an option for a TA within the course table
In a scenario where a user is both a student in a course and a TA for another course, then they would have to create two unique accounts. But if we want the user to be able to sign into their UT ID, then that wouldn't be possible with the current implementation

2024-07-30 00:03 UTC, defkorean requested changes
Biggest things I noticed is style inconsistencies. One of the suggestions I would consider is changing all instances of 'People' to 'User' since I'm noticing the endpoints are using User rather than People. As for functionality, it works well and I haven't run into a bug that crashes the site. Please review these comments and feel free to let me know if any clarification is needed anywhere.

2024-07-30 00:03 UTC, defkorean commented on backend/api/create_tables.sql
>  /* Create Students table */
Update comment to show Users

2024-07-30 00:03 UTC, defkorean commented on backend/api/create_tables.sql
> +    FOREIGN KEY (instructor_id) REFERENCES people (id)
maybe for consistency's sake, we could change this to users rather than people

2024-07-30 00:03 UTC, defkorean commented on backend/api/models.py
> +class People(db.Model):
I believe having Users as the name would be better than just People

2024-07-30 00:03 UTC, defkorean commented on docs/CodeAssist_Design_Doc.md
Good job on adding to the design document.

2024-07-30 00:03 UTC, defkorean commented on frontend/src/pages/home/logInModal.js
> +import {userLogin } from "../../services/user";
small style change here, add a space between the curly brace and userLogin

2024-07-30 00:03 UTC, defkorean commented on frontend/src/pages/home/logInModal.js
> +      // if (role == 'student'){
I'm assuming this code is here for later changes of differentiating roles and doing different things right?

2024-07-30 00:03 UTC, defkorean commented on frontend/src/pages/home/logInModal.js
> +          isTA: res.data?.role == 'TA',
Pretty sure you need to change the '==' to '==='

2024-07-30 00:03 UTC, defkorean commented on frontend/src/pages/home/signUpModal.js
> +    if (role == 'student'){
I believe you need to use '===' here as well by convention

2024-08-06 16:43 UTC, hudsonwhipple commented on backend/api/models.py
> +class People(db.Model):
I agree, I think it should say users in each place instead of people

2024-08-06 16:53 UTC, hudsonwhipple commented on backend/routes/user.py
> +    person = db.session.query(People).filter_by(sis_user_id=insid)
Should it filter by id instead of sis_user_id?

2024-08-06 17:37 UTC, Vellankijay commented on frontend/src/pages/home/logInModal.js
> +      // if (role == 'student'){
It was supposed to earlier, but it serves no function right now.

2024-08-06 18:40 UTC, defkorean commented
Did you mean to close this pull request? None of your commits has been merged to main

2024-08-06 19:32 UTC, Vellankijay commented
> Did you mean to close this pull request? None of your commits has been merged to main

Yes because this current request is very behind main so I am creating a new PR with the updated code

2024-08-06 19:33 UTC, closed without merging